### ISSUE TITLE
SQLiteConnection.Open doesn't throw exception when the file opened is not a SQLite Database

### ISSUE THREAD

**Issue by codeliger** [codeliger/timelord#4]
```
        /// <summary>
        /// Creates the database connection
        /// </summary>
        private void openDatabase()
        {
            sqlite = new SQLiteConnection("Data Source=" + this.filePath + ";Version=3;");

            try
            {
                // No exception is thrown when I try and open a jpeg image.
                sqlite.Open();
            }
            catch(SQLiteException e)
            {
                MessageBox.Show(e.Message + e.StackTrace);
            }
        }
```

**Comment by rensoftworks** [comment]
Did you mean that the exception is not being caught, instead of not being thrown?

Edit: Just looked into it more-- Upon looking further into the documentation, the SQLiteConnection.Open() method doesn't seem to have any exceptions that could possibly be thrown.

The exception that I'm getting is not from the code inside that try/catch block, but within the prepareQueries() method of that same class.

**Comment by rensoftworks** [comment]
Just pushed a commit that moves the try/catch block further up the stack. I'd suggest keeping exception handling code away from the Timesheet class and in the presentation layer stuff, so that error handling is easier (i.e. we don't have to deal with exceptions being thrown after handling previous exceptions.)

**Comment by codeliger** [comment]
I fixed it last night and I forgot to close this issue see commit e80eb9f26e3ec3ee8d6ac1f007dfa6a3c8b35570
